# On commence par fournir un nom
name: Compilation du projet atelier-test-unitaires
# Le on spécifie à quel moment le workflow doit s'exécuter.  Ici, on le
on: 
  push:
  workflow_dispatch: # Permet de déclencher le workflow manuellement depuis l'interface GitHub

jobs:
  compitation: # Nom du 1er job qui s'exécute sur un runner Ubuntu
    runs-on: ubuntu-latest
    # Définition des étapes du workflow
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:                      # Paramètres de configuration pour l'action setup-java
          distribution: 'temurin'
          java-version: '21'
      - name: Ajouter droit pour la compilation
        run: chmod +x mvnw
      - name: Compiler le projet
        run: ./mvnw -Dtest=CalculatriceTest#additionnerDeuxNombresPositifs+soustraireDonneLaDifference+multiplierDeuxNombres+maxRetourneLePlusGrandDesDeuxNombres+estPairDistingueLesNombresPairsEtImpairs+diviserParZeroLanceUneException+estPremierRetourneVraiPourLesNombresPremiersConnus+estPremierGereLesCasLimites+diviserAvecNombresNegatifs
          
  